import type { NextPage } from 'next'
import Head from 'next/head'
import { Cover } from '../components/Cover'
import styles from '../styles/Home.module.css'
import { Container } from '@chakra-ui/react'
import { SocialNetworks } from '../components/SocialNetworks'
import { MoreAbout } from '../components/MoreAbout'
import { PersonalInfo } from '../components/PersonalInfo'
import { ToggleTheme } from '../components/ToggleTheme'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cover />
      <Container maxW={['container.lg', null, 'container.lg']}>
        <ToggleTheme />

        <PersonalInfo />
        <MoreAbout />
      </Container>
    </div>
  )
}

export default Home
