import { Button } from '@chakra-ui/button'
import { useColorMode } from '@chakra-ui/color-mode'
import { MoonIcon, SunIcon } from '@chakra-ui/icons'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Cover } from '../components/Cover'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {


  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       

      <main >
        <Cover/>
        <Button aria-label="toggle theme" variant='ghost' onClick={toggleColorMode} leftIcon={colorMode === 'dark' ? <SunIcon/> : <MoonIcon/>}>
        </Button>
        
      </main>
    </div>
  )
}

export default Home
